[theme]
primary = "#d8dee9"
secondary = "light black"
title = "#88c0d0"
playing = "#8fbcbb"
playing_selected = "#8fbcbb"
playing_bg = "black"
highlight = "#d8dee9"
highlight_bg = "#2e3440"
error = "#d8dee9"
error_bg = "red"
statusbar = "black"
statusbar_progress = "#5e81ac"
statusbar_bg = "#5e81ac"
cmdline = "#d8dee9"
cmdline_bg = "black"
search_match = "light red"
